Add: TableRow component with expensesData info
zh-betina/my-finances pull request #2
Opened 2020-10-28 15:09 UTC by zh-betina

Nie byłam pewna, czy to "już" pora na useState() 😁

2020-10-31 10:49 UTC, nettecode requested changes

2020-10-31 10:49 UTC, nettecode commented on src/Main/Views/Expenses/Table/Table.js
> +                <TableRow date={data[0].date}
Na spotkaniu pogadamy jeszcze o bardziej dynamicznym tworzeniu takich struktur :) Tak na teraz podrzucam: https://pl.reactjs.org/docs/thinking-in-react.html

2020-10-31 10:50 UTC, nettecode commented
> Nie byłam pewna, czy to "już" pora na useState() 😁

Mogła być już. Ale tak na pewno to będzie za chwilę, kiedy dojdziemy do tematu dodawania nowych pozycji do tabeli z wykorzystaniem formularza ;)

2020-11-17 14:18 UTC, zh-betina commented
@nettecode No! Wróciłam :D 
Mam nadzieję, że po takim czasie nic mi nie umknęło, ale chyba jest już bardziej dynamicznie.
Biorę się za następnego taska!

2020-11-17 17:16 UTC, zh-betina commented
@nettecode O jeny... pracowałam na laptopie męża i on korzysta z desktopowej apki GitHub'a, która jest jakoś chyba powiązana z VSC, bo commity i pushe zostały zrobione z jego konta 🙄 pomimo tego, że ja korzystałam z konsoli. Chyba usunę ten commit i go powtórzę ze swojego konta.

2020-11-24 18:21 UTC, nettecode commented
Nie mam więcej uwag, więc merguje ;)

2020-11-24 18:23 UTC, merged